In [1]:
import pandas as pd 
import numpy as np

In [30]:
CPI_data = pd.read_csv('./Monthly_data/CPI-monthly.csv')
ER_data= pd.read_csv('./Monthly_data/Exchange rate Monthly.csv')
Exports_data=pd.read_csv('./Monthly_data/Exports Merchandise Monthly.csv')

In [3]:
pd.set_option('display.max_columns', None)
CPI_data

,Year,Afghanistan,Albania,United Arab Emirates,Armenia,Developing Asia,Antigua and Barbuda,Austria,Azerbaijan,Burundi,Belgium,Benin,Burkina Faso,Bangladesh,Bulgaria,Bahrain,Bahamas,Bosnia and Herzegovina,Belarus,Belize,Bolivia,Brazil,Barbados,Bhutan,Botswana,Central African Republic,Canada,Switzerland,Chile,China,Cote d'Ivoire,"Congo, Dem. Rep.","Congo, Rep.",Colombia,Comoros,Cabo Verde,Costa Rica,Cyprus,Czech Republic,Germany,Developing Countries,Djibouti,Dominica,Denmark,Dominican Republic,Algeria,East Asia & Pacific developing,Europe & Central Asia developing,Ecuador,"Egypt, Arab Rep.",Spain,Estonia,Finland,Fiji,France,Gabon,United Kingdom,Georgia,Guinea,"Gambia, The",Equatorial Guinea,Greece,Grenada,Guatemala,Guyana,High Income Countries,"Hong Kong SAR, China",Honduras,Croatia,Haiti,Hungary,High income: OECD,Indonesia,India,Ireland,Iceland,Israel,Italy,Jamaica,Jordan,Japan,Kazakhstan,Kenya,Kyrgyz Republic,Cambodia,Kiribati,St. Kitts and Nevis,"Korea, Rep.",Latin America & Caribbean developing,"Lao, PDR",Lebanon,Liberia,Libya,St. Lucia,Low Income,Lesotho,Lithuania,Luxembourg,Latvia,Morocco,"Moldova, Rep.",Madagascar,Maldives,Mexico,Middle Income Countries,"Macedonia, FYR",Mali,Malta,Middle East & N. Africa developing,Montenegro,Mozambique,Mauritania,Mauritius,Malawi,Malaysia,Namibia,Nigeria,Nicaragua,Netherlands,Norway,Nepal,High Income: Non-OECD,Oman,Pakistan,Panama,Peru,Philippines,Poland,Portugal,Paraguay,West Bank and Gaza,Qatar,Romania,Russian Federation,Rwanda,South Asia developing,Saudi Arabia,Senegal,Singapore,Solomon Islands,Sierra Leone,El Salvador,San Marino,Serbia,Sub-Saharan Africa developing,Sao Tome and Principe,Suriname,Slovakia,Slovenia,Sweden,Swaziland,Seychelles,Chad,Togo,Thailand,Tajikistan,Timor-Leste,Tonga,Trinidad and Tobago,Tunisia,Turkey,"Taiwan, China",Uganda,Uruguay,United States,St. Vincent and the Grenadines,"Venezuela, RB",Vietnam,World (WBG members),Samoa,"Yemen, Rep.",South Africa,Zambia
0,1988M12,NaN,NaN,NaN,NaN,33.23211,NaN,63.07520,NaN,NaN,63.78632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.00370,NaN,NaN,NaN,NaN,NaN,62.81494,70.44526,21.74755,37.31343,42.60179,NaN,NaN,6.387537,NaN,NaN,6.990050,51.38340,NaN,64.94949,19.44794,NaN,NaN,63.75546,6.994547,NaN,35.12080,NaN,0.690361,15.2,47.61637,NaN,65.52863,NaN,68.19105,NaN,57.61261,NaN,NaN,NaN,NaN,24.15172,NaN,11.77817,NaN,60.30523,48.95449,7.102804,NaN,NaN,NaN,60.51877,11.55401,NaN,57.97254,31.03741,25.04758,51.30152,2.948886,35.36350,90.06211,NaN,8.847364,NaN,NaN,NaN,NaN,40.30609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.17605,NaN,NaN,NaN,NaN,NaN,8.541873,19.48337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.22293,NaN,54.82897,NaN,1.745370,NaN,63.80900,61.38614,NaN,55.00433,NaN,17.08578,68.92052,0.004084,22.58772,2.382716,40.25925,8.538429,NaN,NaN,NaN,NaN,NaN,NaN,70.68182,NaN,69.60738,NaN,NaN,23.51653,NaN,NaN,12.25730,NaN,NaN,NaN,NaN,60.34224,NaN,NaN,NaN,NaN,45.81932,NaN,NaN,NaN,NaN,42.79919,0.033280,66.47697,NaN,0.720415,55.61017,NaN,0.199333,NaN,48.23800,NaN,NaN,19.62482,0.095229
1,1989M01,NaN,NaN,NaN,NaN,34.38592,NaN,63.63636,NaN,NaN,64.02666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.10908,NaN,NaN,NaN,NaN,NaN,63.16247,70.83155,21.99008,38.80597,42.89970,NaN,NaN,6.572541,NaN,NaN,7.064677,51.96588,NaN,65.65657,20.09587,NaN,NaN,63.97380,7.088926,NaN,36.35313,NaN,0.726069,15.1,48.16927,NaN,65.85903,NaN,68.52228,NaN,57.72647,NaN,NaN,NaN,NaN,24.15172,NaN,11.97586,NaN,60.56294,49.44649,7.149533,NaN,NaN,NaN,60.78443,11.62138,NaN,58.71172,31.57263,26.21727,51.62690,3.014417,38.88155,89.85507,NaN,9.123844,NaN,NaN,NaN,NaN,40.37500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.61171,NaN,NaN,NaN,NaN,NaN,8.750965,20.13248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.35032,NaN,55.13078,NaN,1.939300,NaN,63.17601,61.82618,NaN,55.00574,NaN,17.11663,68.92052,0.005976,23.24561,4.278752,40.98107,8.616971,NaN,NaN,NaN,NaN,NaN,NaN,70.45455,NaN,69.57834,NaN,NaN,23.65591,NaN,NaN,12.51015,NaN,NaN,NaN,NaN,61.04273,NaN,NaN,NaN,NaN,46.18920,NaN,NaN,NaN,NaN,43.10345,0.035474,66.47697,NaN,0.752198,55.88706,NaN,0.201556,NaN,48.59190,NaN,NaN,19.91342,0.095229
2,1989M02,NaN,NaN,NaN,NaN,34.60887,NaN,63.74860,NaN,NaN,64.31068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.23094,NaN,NaN,NaN,NaN,NaN,63.59687,71.18759,22.01730,39.05084,42.70109,NaN,NaN,6.796495,NaN,NaN,7.064677,51.70585,NaN,65.85859,20.24848,NaN,NaN,64.41048,7.130872,NaN,36.58909,NaN,0.761778,15.7,48.20389,NaN,66.29956,NaN,68.69324,NaN,57.95418,NaN,NaN,NaN,NaN,24.05274,NaN,12.04869,NaN,60.72843,50.30750,7.242991,NaN,NaN,NaN,60.94789,11.76735,NaN,58.71172,32.01781,26.66095,51.95228,3.014417,40.43721,89.54451,NaN,9.152445,NaN,NaN,NaN,NaN,40.51393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.77927,NaN,NaN,NaN,NaN,NaN,8.869776,20.28537,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.73248,NaN,55.03018,NaN,2.036265,NaN,63.37590,62.04620,NaN,55.24338,NaN,17.21691,68.92052,0.008466,23.46491,5.296946,41.51864,8.860168,NaN,NaN,NaN,NaN,NaN,NaN,70.56818,NaN,69.76182,NaN,NaN,24.11390,NaN,NaN,12.69269,NaN,NaN,NaN,NaN,61.37630,NaN,NaN,NaN,NaN,46.76082,NaN,NaN,NaN,NaN,43.20487,0.037169,67.05680,NaN,0.794576,56.11781,NaN,0.207910,NaN,48.75023,NaN,NaN,20.20202,0.095229
3,1989M03,NaN,NaN,NaN,NaN,35.11426,NaN,63.86083,NaN,NaN,64.46362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.41537,NaN,NaN,NaN,NaN,NaN,63.94440,71.37883,22.43669,39.72715,42.40318,NaN,NaN,6.962025,NaN,NaN,7.077114,51.79946,NaN,65.85859,20.54505,NaN,NaN,64.84716,7.214765,NaN,37.12812,NaN,0.833194,16.2,48.51118,NaN,66.96035,NaN,68.85351,NaN,58.18190,NaN,NaN,NaN,NaN,24.64663,NaN,12.14234,NaN,61.02267,50.30750,7.289720,NaN,NaN,NaN,61.25298,11.80103,NaN,58.71172,32.91817,26.78195,52.38612,3.079948,40.68124,90.06211,NaN,9.304986,NaN,NaN,NaN,NaN,40.79178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.99151,NaN,NaN,NaN,NaN,NaN,8.965845,20.58247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.73248,NaN,55.03018,NaN,2.133230,NaN,63.62021,62.59626,NaN,55.18581,NaN,17.26319,68.92052,0.012052,23.46491,5.525016,41.88605,9.026788,NaN,NaN,NaN,NaN,NaN,NaN,70.45455,NaN,69.69215,NaN,NaN,24.49223,NaN,NaN,12.87354,NaN,NaN,NaN,NaN,61.60979,NaN,NaN,NaN,NaN,46.76082,NaN,NaN,NaN,NaN,43.20487,0.038295,67.21787,NaN,0.858142,56.44086,NaN,0.252126,NaN,49.03835,NaN,NaN,20.49062,0.095229
4,1989M04,NaN,NaN,NaN,NaN,35.52607,NaN,64.08530,NaN,NaN,64.88967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.44173,NaN,NaN,NaN,NaN,NaN,64.11816,71.75445,22.67019,40.24021,42.50248,NaN,NaN,7.137293,NaN,NaN,7.089552,51.97628,NaN,66.26263,20.81199,NaN,NaN,65.28384,7.361577,NaN,37.55897,NaN,0.857000,17.7,48.64210,NaN,67.62115,NaN,69.28091,NaN,58.97891,NaN,NaN,NaN,NaN,25.14154,NaN,12.28800,NaN,61.56158,51.16851,7.289720,NaN,NaN,NaN,61.79282,11.98069,NaN,59.34530,33.61845,27.46763,52.60304,3.079948,41.00661,91.61491,NaN,9.390790,NaN,NaN,NaN,NaN,40.96406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.20375,NaN,NaN,NaN,NaN,NaN,9.099956,20.84991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.36943,NaN,54.92958,NaN,2.327160,NaN,63.94225,62.92629,NaN,55.70963,NaN,17.66430,68.68327,0.017828,23.68421,5.939571,42.30440,9.044039,NaN,NaN,NaN,NaN,NaN,NaN,71.13636,NaN,70.09279,NaN,NaN,24.60175,NaN,NaN,13.11692,NaN,NaN,NaN,NaN,62.21021,NaN,NaN,NaN,NaN,46.86169,NaN,NaN,NaN,NaN,43.40771,0.040679,67.81918,NaN,0.900519,56.81005,NaN,0.286180,NaN,49.49379,NaN,NaN,20.77922,0.095229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2018M07,NaN,116.6109,117.9010,127.5054,134.74600,NaN,117.73290,155.0722,NaN,117.35850,112.4008,112.2244,173.0916,113.1427,119.3722,NaN,104.6025,499.1570,106.0249,148.23770,166.4718,NaN,NaN,152.149,NaN,116.68110,99.70859,130.61160,122.45800,114.99500,NaN,NaN,138.364200,NaN,NaN,128.507500,104.34780,114.3784,112.72730,267.93620,NaN,NaN,112.55460,136.273100,154.6705,125.61350,186.3465,124.742300,281.5,112.12480,123.2232,112.55510,NaN,110.35370,NaN,120.42740,130.6736,NaN,NaN,NaN,104.76110,NaN,140.96350,NaN,113.77620,131.85730,148.411200,109.5341,NaN,120.5966,113.41030,150.61760,169.8663,107.49740,127.46100,109.14920,111.38830,164.089100,127.40210,104.55490,NaN,182.658000,162.5478,NaN,NaN,NaN,116.00020,642.6088,136.7264,129.8544,NaN,NaN,NaN,NaN,150.2954,116.4497,114.99110,115.0327,112.4883,162.0996,NaN,NaN,137.706900,268.74710,113.7162,115.9956,113.4399,195.8921,117.1492,189.3563,NaN,130.70060,NaN,120.52310,154.0603,255.425200,160.3416,115.80230,120.24200,NaN,122.40890,116.4294,176.48870,125.14830,128.788600,128.72810,113.385300,112.34350,142.496500,112.1607,116.8312,122.1554,179.1093,NaN,170.6408,122.15910,107.5665,115.96270,NaN,NaN,111.92750,NaN,148.2496,192.20210,NaN,298.2301,112.9679,111.5655,110.18710,NaN,NaN,NaN,113.4500,114.32410,171.1706,NaN,NaN,152.9915,151.11560,206.474400,110.02900,177.2928,195.010100,116.29950,NaN,NaN,165.8320,159.61180,NaN,NaN,156.56570,200.857100
356,2018M08,NaN,117.0569,118.0702,128.2709,135.48130,NaN,117.73290,156.4677,NaN,117.52240,111.7063,110.4208,175.4628,113.2367,118.8341,NaN,104.4979,499.8022,106.4288,148.48600,166.3222,NaN,NaN,152.149,NaN,116.59430,99.69224,130.83200,123.30920,115.09430,NaN,NaN,138.529700,NaN,NaN,128.420400,105.03430,114.4865,112.82830,269.31510,NaN,NaN,112.11790,136.315000,155.8291,126.33380,187.7669,125.079200,286.5,112.28500,123.8101,112.77530,NaN,110.88790,NaN,121.30300,131.2953,NaN,NaN,NaN,104.41560,NaN,141.58780,NaN,114.00960,131.85730,149.065400,109.5341,NaN,120.6532,113.65060,150.53900,170.5954,107.81410,127.69610,109.25700,111.82210,165.661900,127.58520,105.17600,NaN,183.220500,161.8471,NaN,NaN,NaN,116.60040,643.3351,137.3283,130.0971,NaN,NaN,NaN,NaN,151.0617,116.0095,116.55500,114.9237,112.3944,161.8242,NaN,NaN,138.510300,270.13110,114.0392,115.8868,113.5299,198.1599,117.0379,189.8466,NaN,129.80890,NaN,120.72430,154.1763,258.101400,159.9687,115.93560,119.80200,NaN,122.47610,116.3198,176.85130,125.14830,128.958200,129.82460,113.385300,111.95550,142.777000,112.1405,117.1530,122.4974,179.1272,NaN,171.4335,121.93180,110.0204,116.45160,NaN,NaN,112.21620,NaN,148.7062,193.25900,NaN,300.4425,113.2353,111.6521,109.95360,NaN,NaN,NaN,112.2992,114.62680,172.5405,NaN,NaN,152.9915,151.62270,211.213900,109.95380,178.8060,196.323800,116.36420,NaN,NaN,166.5862,160.11560,NaN,NaN,156.42140,201.428400
357,2018M09,NaN,117.2798,117.3614,128.6550,136.05860,NaN,118.63080,156.7807,NaN,117.52240,NaN,NaN,178.6175,113.5214,117.9372,NaN,105.0209,503.8510,106.4288,148.35460,167.1205,NaN,NaN,152.149,NaN,116.15990,99.75168,131.28370,124.17210,114.29990,NaN,NaN,138.753700,NaN,NaN,128.706500,105.93930,114.1622,113.23230,271.49300,NaN,NaN,111.79040,136.419900,155.9015,127.06260,191.8066,125.568400,293.8,112.55870,123.8629,112.99560,NaN,110.65280,NaN,121.43050,131.7098,NaN,NaN,NaN,106.51700,NaN,142.43050,NaN,114.10970,132.10330,149.112100,110.4009,NaN,121.0308,113.76140,150.26950,170.3524,107.39180,128.02120,109.36470,111.27980,167.496700,127.35130,105.27950,NaN,185.089100,161.9745,NaN,NaN,NaN,117.36720,646.0735,138.3357,130.7039,NaN,NaN,NaN,NaN,151.7165,117.5611,116.82310,115.6863,112.6761,162.0555,NaN,NaN,139.096100,272.31830,113.9433,115.9956,114.2841,201.0773,117.1492,190.0522,NaN,129.93630,NaN,121.22740,155.3364,260.263700,160.7668,115.43590,120.46200,NaN,122.32120,116.2103,176.75100,125.14830,129.205400,131.03070,113.580200,113.21820,143.338000,112.0698,115.8442,123.0725,179.4138,NaN,171.4044,121.70450,110.7362,116.42260,NaN,NaN,112.26600,NaN,148.2496,194.52070,NaN,301.7699,113.3021,112.1173,110.45730,NaN,NaN,NaN,111.9156,114.96300,NaN,NaN,NaN,153.1339,152.33270,224.530400,110.13640,180.2985,197.298400,116.49940,NaN,NaN,167.5668,160.66900,NaN,NaN,157.14290,201.818900
358,2018M10,NaN,117.0569,NaN,NaN,136.44080,NaN,NaN,157.0943,NaN,118.31990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,506.4217,NaN,148.61750,167.8724,NaN,NaN,NaN,NaN,NaN,99.92793,131.75760,124.41700,NaN,NaN,NaN,138.919200,NaN,NaN,129.179100,106.39690,114.5946,113.43430,272.99200,NaN,NaN,112.11790,NaN,NaN,127.32320,194.0135,125.510000,301.4,113.57140,124.4674,NaN,NaN,110.77040,NaN,NaN,132.1244,NaN,NaN,NaN,107.33950,NaN,142.90920,NaN,NaN,NaN,149.953300,NaN,NaN,121.6538,NaN,150.68490,170.8384,107.28620,128.74650,NaN,111.27980,NaN,127.18860,NaN,NaN,183.611400,NaN,NaN,NaN,NaN,117.16720,648.8095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.3130,116.94590,116.4488,NaN,162.6794,NaN,NaN,139.817000,273.82780,114.2851,115.5604,NaN,NaN,NaN,190.1945,NaN,130.44590,NaN,NaN,NaN,NaN,161.5947,115.84680,120.24200,NaN,NaN,NaN,181.25580,NaN,129.311000,131.35960,NaN,113.21820,144.179500,NaN,NaN,123.7123,180.0418,NaN,172.2814,NaN,NaN,NaN,NaN,NaN,112.52490,NaN,NaN,NaN,NaN,NaN,NaN,112.4743,NaN,NaN,NaN,NaN,NaN,115.03030,NaN,NaN,NaN,NaN,154.05680,230.522200,110.22230,179.6603,197.754000,NaN,NaN,NaN,168.1249,NaN,NaN,NaN,NaN,203.237800
359,2018M11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
ER_data

,Period,Afghanistan,Angola,Albania,United Arab Emirates,Argenti0,Armenia,Developing Asia,Antigua and Barbuda,Australia,Austria,Azerbaijan,Burundi,Belgium,Benin,Burki0 Faso,Bangladesh,Bulgaria,Bahrain,Bahamas,Bosnia and Herzegovi0,Belarus,Belize,Bolivia,Brazil,Barbados,Brunei Darussalam,Bhutan,Botswa0,Central African Republic,Ca0da,Switzerland,Chile,Chi0,Cote d'Ivoire,Cameroon,"Congo, Dem. Rep.","Congo, Rep.",Colombia,Comoros,Cabo Verde,Costa Rica,Cyprus,Czech Republic,Germany,Developing Countries,Djibouti,Dominica,Denmark,Dominican Republic,Algeria,East Asia & Pacific developing,Europe & Central Asia developing,Ecuador,"Egypt, Arab Rep.",Eritrea,Spain,Estonia,Ethiopia,Finland,Fiji,France,"Micronesia, Fed. Sts.",Gabon,United Kingdom,Georgia,Gha0,Guinea,"Gambia, The",Guinea-Bissau,Equatorial Guinea,Greece,Gre0da,Guatemala,Guya0,High Income Countries,"Hong Kong SAR, Chi0",Honduras,Croatia,Haiti,Hungary,High income: OECD,Indonesia,India,Ireland,"Iran, Islamic Rep.",Iraq,Iceland,Israel,Italy,Jamaica,Jordan,Japan,Kazakhstan,Kenya,Kyrgyz Republic,Cambodia,Kiribati,St. Kitts and Nevis,"Korea, Rep.",Kuwait,Latin America & Caribbean developing,"Lao, PDR",Lebanon,Liberia,Libya,St. Lucia,Low Income,Sri Lanka,Lesotho,Lithuania,Luxembourg,Latvia,Morocco,"Moldova, Rep.",Madagascar,Maldives,Mexico,Middle Income Countries,"Macedonia, FYR",Mali,Malta,Myanmar,Middle East & N. Africa developing,Montenegro,Mongolia,Mozambique,Mauritania,Mauritius,Malawi,Malaysia,0mibia,Niger,Nigeria,Nicaragua,Netherlands,Norway,Nepal,New Zealand,High Income: Non-OECD,Oman,Pakistan,Pa0ma,Peru,Philippines,Papua New Guinea,Poland,Portugal,Paraguay,West Bank and Gaza,Qatar,Romania,Russian Federation,Rwanda,South Asia developing,Saudi Arabia,Sudan,Senegal,Singapore,Solomon Islands,Sierra Leone,El Salvador,San Marino,Serbia,South Sudan,Sub-Saharan Africa developing,Sao Tome and Principe,Suri0me,Slovakia,Slovenia,Sweden,Swaziland,Seychelles,Syrian Arab Republic,Chad,Togo,Thailand,Tajikistan,Turkmenistan,Timor-Leste,Tonga,Trinidad and Tobago,Tunisia,Turkey,"Taiwan, Chi0","Tanzania, United Rep.",Uganda,Ukraine,Uruguay,United States,Uzbekistan,St. Vincent and the Gre0dines,"Venezuela, RB",Viet0m,Vanuatu,World (WBG members),Samoa,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
0,1988M12,0.0,0.0000,0.0000,3.675,0.00000,0.0,190.3592,0.000000,1.164807,0.842486,0.000000,0.000,0.842486,0.0,0.0,0.00000,0.000000,0.378000,0.0,0.000000,0.00,0,0.00,0.000000,0.000000,0.000000,15.01773,0.00000,0.0,1.196500,1.480864,245.7682,3.731000,0.0000,0.0,0.000,0.0,0.000,0.0000,0.0,0.0000,0.842486,0.00000,0.842486,0.000,0.0,0.0,6.793227,0.00000,0.0000,263.5328,0.0000,1,0.00000,0.0,0.842486,0.842486,0.00000,0.842486,0.000000,0.842486,0,0.0,0.548072,0.000000,0.000000,0.000,0.00000,0.0,0.0,0.842486,0.0,0.000000,0.0,34.98479,7.806273,0.00000,0.000000,0.00000,0.0000,36.71427,0.00,15.01773,0.842486,0.0,0.0,0.0000,1.644909,0.842486,0.0000,0.514000,123.6641,0.0000,18.62000,0.00000,0.0,0.0,0.0,687.8727,0.278409,0.00,0.0,0.000,0.0,0.0,0.0,0.000,33.01864,2.349682,0.842486,0.842486,0.842486,8.337500,0.00000,0.000,0.00000,2.281000,0.000,0.00000,0.0,0.842486,0.0,0.0,0.0,0.000,0.00000,0.0000,0.00000,0.0000,2.694045,2.349682,0.0,0.0000,0.00000,0.842486,6.526227,0.0000,1.566983,0.000000,0.387955,18.64750,1,0.000000,0.00000,0.000000,0.000000,0.842486,0.000,1,3.642000,0.001000,0.00000,0.0000,16.17234,3.752000,0.0,0.0,1.944500,0.000000,0.000,0.00,0.0,0.0,0.0,0.0000,0.0,0.000000,0.842486,0.842486,6.091182,2.349682,0.00000,0.0,0.0,0.0,25.15591,0.0,0,0,0.000000,0.000000,0.885455,0.002000,28.19955,125.1250,0.000,0.00000,0.00000,1,0.000,0.0,0.0,0.00,0.0000,76.76546,0.000000,0.0000,2.349682,0.00000,0.0
1,1989M01,0.0,0.0000,0.0000,3.675,0.00000,0.0,191.0076,0.000000,1.148810,0.874694,0.000000,0.000,0.874694,0.0,0.0,0.00000,0.000000,0.378000,0.0,0.000000,0.00,0,0.00,0.000000,0.000000,0.000000,15.07864,0.00000,0.0,1.191909,1.560364,247.1382,3.731000,0.0000,0.0,0.000,0.0,0.000,0.0000,0.0,0.0000,0.874694,0.00000,0.874694,0.000,0.0,0.0,7.106364,0.00000,0.0000,264.0013,0.0000,1,0.00000,0.0,0.874694,0.874694,0.00000,0.874694,0.000000,0.874694,0,0.0,0.562866,0.000000,0.000000,0.000,0.00000,0.0,0.0,0.874694,0.0,0.000000,0.0,35.41262,7.805545,0.00000,0.000000,0.00000,0.0000,37.16490,0.00,15.07864,0.874694,0.0,0.0,0.0000,1.685000,0.874694,0.0000,0.529432,127.2977,0.0000,18.71409,0.00000,0.0,0.0,0.0,685.4045,0.284955,0.00,0.0,0.000,0.0,0.0,0.0,0.000,33.13114,2.385500,0.874694,0.874694,0.874694,8.371591,0.00000,0.000,0.00000,2.282318,0.000,0.00000,0.0,0.874694,0.0,0.0,0.0,0.000,0.00000,0.0000,0.00000,0.0000,2.722182,2.385500,0.0,0.0000,0.00000,0.874694,6.678818,0.0000,1.596001,3.029721,0.385909,18.91386,1,0.000000,0.00000,0.000000,0.000000,0.874694,0.000,1,3.642000,0.001000,0.00000,0.0000,16.25547,3.752000,0.0,0.0,1.941273,0.000000,0.000,0.00,0.0,0.0,0.0,0.0000,0.0,0.000000,0.874694,0.874694,6.268909,2.385500,0.00000,0.0,0.0,0.0,25.30182,0.0,0,0,1.136364,0.000000,0.921250,0.002000,27.92000,125.6875,0.000,0.00000,0.00000,1,0.000,0.0,0.0,0.00,0.0000,77.67523,0.000000,0.0000,2.385500,0.00000,0.0
2,1989M02,0.0,0.0000,0.0000,3.675,0.00000,0.0,191.9781,0.000000,1.169614,0.883210,0.000000,0.000,0.883210,0.0,0.0,0.00000,0.000000,0.378000,0.0,0.000000,0.00,0,0.00,0.000000,0.000000,0.000000,15.23600,0.00000,0.0,1.189250,1.573950,245.8500,3.731000,0.0000,0.0,0.000,0.0,0.000,0.0000,0.0,0.0000,0.883210,0.00000,0.883210,0.000,0.0,0.0,7.208200,0.00000,0.0000,264.2489,0.0000,1,0.00000,0.0,0.883210,0.883210,0.00000,0.883210,0.000000,0.883210,0,0.0,0.570153,0.000000,0.000000,0.000,0.00000,0.0,0.0,0.883210,0.0,0.000000,0.0,35.33238,7.801050,0.00000,0.000000,0.00000,0.0000,37.08043,0.00,15.23600,0.883210,0.0,0.0,0.0000,1.685000,0.883210,0.0000,0.547500,127.6755,0.0000,18.83050,0.00000,0.0,0.0,0.0,680.2200,0.288100,0.00,0.0,0.000,0.0,0.0,0.0,0.000,33.10250,2.458750,0.883210,0.883210,0.883210,8.433500,0.00000,0.000,0.00000,2.475000,0.000,0.00000,0.0,0.883210,0.0,0.0,0.0,0.000,0.00000,0.0000,0.00000,0.0000,2.730850,2.458750,0.0,0.0000,0.00000,0.883210,6.724150,0.0000,1.616534,3.028403,0.386000,19.06750,1,0.000000,0.00000,0.000000,0.000000,0.883210,0.000,1,3.642000,0.001000,0.00000,0.0000,16.40952,3.752550,0.0,0.0,1.928500,0.000000,0.000,0.00,0.0,0.0,0.0,0.0000,0.0,0.000000,0.883210,0.883210,6.323300,2.458750,0.00000,0.0,0.0,0.0,25.38350,0.0,0,0,1.168727,0.000000,0.940350,0.002000,27.70300,127.7250,0.000,0.00000,0.00000,1,0.000,0.0,0.0,0.00,0.0000,77.53630,0.000000,0.0000,2.458750,0.00000,0.0
3,1989M03,0.0,0.0000,0.0000,3.675,0.00000,0.0,193.4470,0.000000,1.223637,0.890488,0.000000,0.000,0.890488,0.0,0.0,0.00000,0.000000,0.378000,0.0,0.000000,0.00,0,0.00,0.000000,0.000000,0.000000,15.45522,0.00000,0.0,1.195565,1.611304,246.3096,3.731000,0.0000,0.0,0.000,0.0,0.000,0.0000,0.0,0.0000,0.890488,0.00000,0.890488,0.000,0.0,0.0,7.291391,0.00000,0.0000,264.5445,0.0000,1,0.00000,0.0,0.890488,0.890488,0.00000,0.890488,0.000000,0.890488,0,0.0,0.583451,0.000000,0.000000,0.000,0.00000,0.0,0.0,0.890488,0.0,0.000000,0.0,35.59831,7.797739,0.00000,0.000000,0.00000,0.0000,37.36052,0.00,15.45522,0.890488,0.0,0.0,0.0000,1.690870,0.890488,0.0000,0.538043,130.5509,0.0000,19.20130,0.00000,0.0,0.0,0.0,675.6761,0.290217,0.00,0.0,0.000,0.0,0.0,0.0,0.000,33.42804,2.539391,0.890488,0.890488,0.890488,8.475217,0.00000,0.000,0.00000,2.475000,0.000,0.00000,0.0,0.890488,0.0,0.0,0.0,0.000,0.00000,0.0000,0.00000,0.0000,2.753609,2.539391,0.0,0.0000,0.00000,0.890488,6.805957,0.0000,1.622369,3.029622,0.386217,19.41370,1,0.000000,0.00000,0.000000,0.000000,0.890488,0.000,1,3.642000,0.001000,0.00000,0.0000,16.64788,3.751783,0.0,0.0,1.939478,0.000000,0.000,0.00,0.0,0.0,0.0,0.0000,0.0,0.000000,0.890488,0.890488,6.393304,2.539391,0.00000,0.0,0.0,0.0,25.47174,0.0,0,0,1.241492,0.000000,0.943978,0.002000,27.61783,130.4565,0.000,0.00000,0.00000,1,0.000,0.0,0.0,0.00,0.0000,78.12339,0.000000,0.0000,2.539391,0.00000,0.0
4,1989M04,0.0,0.0000,0.0000,3.675,0.00000,0.0,195.0895,0.000000,1.243114,0.890342,0.000000,0.000,0.890342,0.0,0.0,0.00000,0.000000,0.378000,0.0,0.000000,0.00,0,0.00,0.000000,0.000000,0.000000,15.70650,0.00000,0.0,1.188900,1.646950,252.2410,3.731000,0.0000,0.0,0.000,0.0,0.000,0.0000,0.0,0.0000,0.890342,0.00000,0.890342,0.000,0.0,0.0,7.280400,0.00000,0.0000,264.6188,0.0000,1,0.00000,0.0,0.890342,0.890342,0.00000,0.890342,0.000000,0.890342,0,0.0,0.587579,0.000000,0.000000,0.000,0.00000,0.0,0.0,0.890342,0.0,0.000000,0.0,35.73175,7.783300,0.00000,0.000000,0.00000,0.0000,37.50110,0.00,15.70650,0.890342,0.0,0.0,0.0000,1.820000,0.890342,0.0000,0.538000,132.0390,0.0000,19.37300,0.00000,0.0,0.0,0.0,672.1200,0.290850,0.00,0.0,0.000,0.0,0.0,0.0,0.000,34.02350,2.548200,0.890342,0.890342,0.890342,8.491500,0.00000,0.000,0.00000,2.475000,0.000,0.00000,0.0,0.890342,0.0,0.0,0.0,0.000,0.00000,0.0000,0.00000,0.0000,2.721150,2.548200,0.0,0.0000,0.00000,0.890342,6.796500,0.0000,1.632956,3.029086,0.386000,19.84450,1,0.000000,0.00000,0.000000,0.000000,0.890342,0.000,1,3.642000,0.001000,0.00000,0.0000,16.93112,3.751050,0.0,0.0,1.950450,0.000000,0.000,0.00,0.0,0.0,0.0,0.0000,0.0,0.000000,0.890342,0.890342,6.369000,2.548200,0.00000,0.0,0.0,0.0,25.52250,0.0,0,0,1.215517,0.000000,0.944200,0.002000,26.96330,132.2250,0.000,0.00000,0.00000,1,0.000,0.0,0.0,0.00,0.0000,78.43185,0.000000,0.0000,2.548200,0.00000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2018M07,0.0,253.7293,107.8486,3.673,27.59330,0.0,1411.2090,2.699545,1.351000,0.855673,1.697886,1780.416,0.855673,0.0,0.0,83.93938,1.673773,0.379068,1.0,1.681886,19834.07,0,6.91,3.824659,2.000977,1.356864,68.73895,10.29523,0.0,1.313545,0.994386,651.9882,6.719159,571.6634,0.0,1619.955,0.0,2885.412,420.9956,0.0,567.7273,0.855673,22.11086,0.855673,5065.074,0.0,0.0,6.376886,49.50986,117.5970,1757.4950,832.0435,1,17.89689,0.0,0.855673,0.855673,27.47425,0.855673,2.099168,0.855673,0,0.0,0.759413,2.448727,4.758795,9067.929,48.00290,0.0,0.0,0.855673,0.0,7.494159,0.0,46.89484,7.847955,23.99052,6.330318,65.96814,277.7284,48.97821,14417.57,68.73895,0.855673,0.0,0.0,106.4664,3.644386,0.855673,131.6790,0.709909,111.4536,344.5050,100.65700,68.20334,0.0,0.0,0.0,1123.3590,0.302955,11791.61,0.0,1513.231,0.0,0.0,0.0,1208.711,159.41250,13.390480,0.855673,0.855673,0.855673,9.461523,16.67091,3357.551,15.48559,18.998020,5125.823,52.70632,0.0,0.855673,0.0,0.0,0.0,2461.981,58.74852,355.7223,34.40700,723.9305,4.050886,13.390430,0.0,361.5498,31.67789,0.855673,8.129114,110.0202,1.473530,8.361239,0.385000,124.50750,1,3.276886,53.42391,3.295889,3.699000,0.855673,5721.170,1,3.655477,3.978591,62.83027,872.0777,77.24887,3.750000,0.0,0.0,1.363523,7.917435,7955.466,8.75,0.0,0.0,0.0,422.1706,0.0,7.506227,0.855673,0.855673,8.819045,13.390430,13.51466,0.0,0.0,0.0,33.27314,0.0,0,0,2.252515,6.823409,2.639659,4.772955,30.56614,2276.7640,3758.407,26.42550,31.13893,1,7939.079,0.0,129724.0,23100.55,108.9250,1585.97000,2.590986,250.3023,13.390430,9.91025,0.0
356,2018M08,0.0,266.1822,108.9400,3.673,30.24126,0.0,1425.0790,2.701522,1.365333,0.866315,1.697261,1778.990,0.866315,0.0,0.0,83.92822,1.694652,0.377478,1.0,1.703457,20457.28,0,6.91,3.934891,2.000957,1.362348,69.61543,10.56340,0.0,1.304000,0.988348,659.4991,6.846739,578.5249,0.0,1620.630,0.0,2969.047,426.1813,0.0,569.9250,0.866315,22.25776,0.866315,7540.499,0.0,0.0,6.459543,49.76359,118.3935,1774.8050,853.8817,1,17.88170,0.0,0.866315,0.866315,27.63867,0.866315,2.114047,0.866315,0,0.0,0.776854,2.534913,4.771087,9092.230,48.74005,0.0,0.0,0.866315,0.0,7.510304,0.0,46.87079,7.849630,24.02078,6.433500,67.95363,279.9661,48.92625,14565.09,69.61543,0.866315,0.0,0.0,107.6504,3.661457,0.866315,136.2439,0.709739,111.0300,357.7837,100.62260,68.73267,0.0,0.0,0.0,1121.3310,0.303196,19285.43,0.0,1511.676,0.0,0.0,0.0,1209.265,160.43000,14.126610,0.866315,0.866315,0.866315,9.476239,16.61511,3311.368,15.52278,18.858090,7642.803,53.33830,0.0,0.866315,0.0,0.0,0.0,2461.687,58.89185,356.7776,34.49061,722.9528,4.094000,14.126780,0.0,362.2754,31.85150,0.866315,8.343261,111.4791,1.499446,8.853607,0.385000,122.98000,1,3.290413,53.29080,3.312218,3.712391,0.866315,5780.765,1,3.655174,4.022370,66.47593,877.2161,77.87157,3.750674,0.0,0.0,1.369000,7.898405,8219.295,8.75,0.0,0.0,0.0,423.7852,0.0,7.504261,0.866315,0.866315,9.075348,14.126980,13.46511,0.0,0.0,0.0,33.02228,0.0,0,0,2.266071,6.749413,2.743413,5.942696,30.71911,2280.9660,3733.038,27.57539,31.35428,1,7883.981,0.0,213716.5,23293.26,110.0105,2337.68100,2.585069,250.2846,14.126850,10.08304,0.0
357,2018M09,0.0,286.0590,108.5063,3.673,38.64783,0.0,1448.6440,2.700250,1.388744,0.857495,1.698000,1784.000,0.857495,0.0,0.0,83.82198,1.677375,0.377000,1.0,1.686150,21190.38,0,6.91,4.102400,2.000850,1.364325,72.22203,10.77763,0.0,1.303725,0.968175,679.4698,6.855400,578.7612,0.0,1621.375,0.0,3031.533,421.8135,0.0,581.0473,0.857495,21.97240,0.857495,7674.845,0.0,0.0,6.395825,49.89270,118.0113,1803.8840,880.2203,1,17.91505,0.0,0.857495,0.857495,27.68738,0.857495,2.127835,0.857495,0,0.0,0.765895,2.609200,4.841500,9095.692,49.26438,0.0,0.0,0.857495,0.0,7.663475,0.0,47.13862,7.837675,24.03953,6.369700,69.74503,278.4145,49.12397,14864.75,72.22203,0.857495,0.0,0.0,110.5850,3.589275,0.857495,136.5519,0.710000,112.0905,367.8721,100.84600,69.23965,0.0,0.0,0.0,1120.0010,0.303000,19669.19,0.0,1510.403,0.0,0.0,0.0,1219.691,165.20700,14.748180,0.857495,0.857495,0.857495,9.402350,16.78850,3412.167,15.50110,19.001850,7780.309,52.81013,0.0,0.857495,0.0,0.0,0.0,2496.553,60.44695,357.3950,34.35160,724.0691,4.140725,14.748230,0.0,362.6958,32.10425,0.857495,8.245500,115.6587,1.515368,10.418460,0.385000,123.19080,1,3.310250,53.97598,3.326139,3.686425,0.857495,5854.810,1,3.659225,3.982600,67.60390,878.9235,80.18285,3.750825,0.0,0.0,1.371350,7.960640,8336.868,8.75,0.0,0.0,0.0,427.8830,0.0,7.496150,0.857495,0.857495,8.945150,14.748280,13.53465,0.0,0.0,0.0,32.59703,0.0,0,0,2.280193,6.766200,2.777425,6.297250,30.74175,2283.0420,3800.272,28.18975,32.87670,1,8018.261,0.0,0.0,23286.50,111.1823,2376.23400,2.603659,250.2786,14.748280,10.94930,0.0
358,2018M10,0.0,303.7345,109.0561,3.673,37.06159,0.0,1473.6990,2.704348,1.407934,0.870907,1.696370,1799.053,0.870907,0.0,0.0,84.52207,1.703630,0.377000,1.0,1.705174,21256.09,0,6.91,3.760022,2.000891,1.372109,73.58743,10.73582,0.0,1.301826,0.993913,679.5872,6.926804,585.1240,0.0,1623.293,0.0,3095.854,428.4075,0.0,595.9065,0.870907,22.49357,0.870907,7796.166,0.0,0.0,6.496565,49.96380,118.7490,1834.9400,884.4504,1,17.91526,0.0,0.870907,0.870907,27.88339,0.870907,2.144862,0.870907,0,0.0,0.768699,2.662804,4.873130,9130.136,49.99641,0.0,0.0,0.870907,0.0,7.728457,0.0,47.50429,7.838043,24.06996,6.465326,71.26059,281.9780,49.52488,15177.11,73.58743,0.870907,0.0,0.0,117.2176,3.657239,0.870907,132.0431,0.709783,112.7609,367.1807,101.11020,69.26480,0.0,0.0,0.0,1131.2240,0.303522,20053.73,0.0,1510.775,0.0,0.0,0.0,1223.629,171.52650,14.536870,0.870907,0.870907,0.870907,9.486413,17.01315,3495.812,15.45728,19.218090,7905.141,53.60380,0.0,0.870907,0.0,0.0,0.0,2562.718,60.38548,356.9950,34.51874,727.9566,4.158522,14.536870,0.0,363.3820,32.16039,0.870907,8.259848,117.7762,1.532541,10.132090,0.385000,129.90450,1,3.334696,53.94120,3.355461,3.749739,0.870907,5953.722,1,3.659130,4.062804,65.86035,876.9750,82.12067,3.751109,0.0,0.0,1.379674,8.017561,8415.225,8.75,0.0,0.0,0.0,430.3051,0.0,7.514413,0.870907,0.870907,9.050152,14.536910,13.62441,0.0,0.0,0.0,32.79483,0.0,0,0,2.271729,6.740674,2.841348,5.819891,30.88115,2287.3500,3780.230,28.11041,32.90704,1,8209.098,0.0,0.0,23323.63,111.3950,2411.72600,2.632711,250.2947,14.536910,11.88980,0.0
359,2018M11,0.0,309.2843,109.4100,3.673,35.60083,0.0,1445.6860,2.710000,1.383155,0.876683,1.697167,1797.333,0.876683,0.0,0.0,83.78050,1.715000,0.377000,1.0,1.722000,21241.25,0,6.91,3.730000,1.997500,1.367000,73.00600,10.63910,0.0,1.311333,1.003833,681.0383,6.919500,593.5750,0.0,1618.167,0.0,3165.912,431.1355,0.0,622.7500,0.876683,22.65817,0.876683,7686.535,0.0,0.0,6.540333,49.92633,118.5503,1799.6840,885.2643,1,17.91783,0.0,0.876683,0.876683,28.01483,0.876683,2.123943,0.876683,0,0.0,0.766003,2.732500,4.847833,9141.518,49.80500,0.0,0.0,0.876683,0.0,7.714333,0.0,47.41194,7.829667,24.13358,6.519667,65.27580,282.1483,49.44216,14815.67,73.00600,0.876683,0.0,0.0,121.0950,3.683167,0.876683,127.5383,0.709667,113.3717,371.0100,101.68830,69.78783,0.0,0.0,0.0,1124.3120,0.304000,20464.05,0.0,1513.667,0.0,0.0,0.0,1223.691,174.51670,14.182830,0.876683,0.876683,0.876683,9.505667,17.09083,3564.695,15.53967,19.964000,7791.901,53.92183,0.0,0.876683,0.0,0.0,0.0,2561.630,60.65500,356.9950,34.63333,728.4688,4.168750,14.182830,0.0,363.2717,32.21333,0.876683,8.359500,117.1140,1.492633,9.861645,0.385000,133.56900,1,3.363500,53.01167,3.365120,3.771000,0.876683,5957.000,1,3.654833,4.086167,66.18917,891.1267,82.00213,3.751000,0.0,0.0,1.374333,8.043360,8429.246,8.75,0.0,0.0,0.0,430.8004,0.0,7.478667,0.876683,0.876683,9.042667,14.183000,13.49983,0.0,0.0,0.0,32.90383,0.0,0,0,2.265871,6.743500,2.886833,5.416167,30.73967,2287.6550,3748.623,27.98317,32.75317,1,8251.382,0.0,0.0,23318.17,110.4588,2380.95300,2.604273,250.2600,14.183170,11.78267,0.0

In [6]:
Exports_data

,Year,Argentina,Developing Asia,Australia,Belgium,Brazil,Canada,Chile,China,Czech Republic,Germany,Developing Countries,Denmark,East Asia & Pacific developing,Europe & Central Asia developing,Spain,Estonia,Finland,France,United Kingdom,High Income Countries,"Hong Kong SAR, China",Hungary,High income: OECD,Indonesia,Israel,Italy,Jordan,Japan,"Korea, Rep.",Latin America & Caribbean developing,Low Income,Mexico,Middle Income Countries,Middle East & N. Africa developing,Malaysia,Netherlands,Norway,New Zealand,High Income: Non-OECD,Peru,Philippines,Poland,Russian Federation,South Asia developing,Singapore,Sub-Saharan Africa developing,Slovakia,Sweden,Thailand,Turkey,"Taiwan, China",Uganda,United States,World (WBG members)
0,1991M01,1265.303,3313.754,5502.346,NaN,4896.404,NaN,NaN,NaN,NaN,44250.68,13522.17,NaN,3313.754,2.651407,7260.230,NaN,NaN,NaN,NaN,262499.9,7752.724,NaN,247282.3,NaN,NaN,NaN,NaN,21646.47,3178.191,10915.59,NaN,5309.358,13522.17,NaN,NaN,NaN,6478.726,1096.959,18300.85,NaN,NaN,NaN,NaN,NaN,4014.566,NaN,NaN,5493.817,3313.754,2.651407,5268.258,NaN,41353.47,168083.9
1,1991M02,1518.856,NaN,5708.852,NaN,3887.668,NaN,NaN,NaN,NaN,40788.13,NaN,NaN,NaN,NaN,7933.039,NaN,NaN,NaN,NaN,255747.3,6063.831,NaN,246204.4,NaN,NaN,NaN,NaN,24397.84,3327.193,10006.73,NaN,5468.340,NaN,NaN,NaN,NaN,5928.947,1271.097,14918.86,NaN,NaN,NaN,NaN,NaN,3175.083,NaN,NaN,5402.757,3152.839,2.588754,4161.086,NaN,40909.06,NaN
2,1991M03,1632.372,NaN,6890.402,NaN,4384.693,NaN,NaN,NaN,NaN,43429.16,NaN,NaN,NaN,NaN,7689.405,NaN,NaN,NaN,NaN,283965.3,6465.924,NaN,272547.5,NaN,NaN,NaN,NaN,28909.44,3921.644,10908.97,NaN,5814.881,NaN,NaN,NaN,NaN,6101.730,1241.708,17017.90,NaN,NaN,NaN,NaN,NaN,4062.258,NaN,NaN,5898.220,4010.966,3.935234,4857.343,NaN,46101.14,NaN
3,1991M04,1884.038,NaN,6524.655,NaN,5119.613,NaN,NaN,NaN,NaN,41399.08,NaN,NaN,NaN,NaN,8670.582,NaN,NaN,NaN,NaN,276742.4,7942.736,NaN,262136.9,NaN,NaN,NaN,NaN,24394.36,4006.248,12160.61,NaN,6250.205,NaN,NaN,NaN,NaN,6996.172,1239.873,18501.62,NaN,NaN,NaN,NaN,NaN,3896.417,NaN,NaN,6062.707,3425.034,3.178725,4778.434,NaN,45152.55,NaN
4,1991M05,2302.835,NaN,7145.694,NaN,4917.469,NaN,NaN,NaN,NaN,41793.64,NaN,NaN,NaN,NaN,7721.173,NaN,NaN,NaN,NaN,280063.6,8551.586,NaN,262021.1,NaN,NaN,NaN,NaN,24739.38,4210.819,11844.38,NaN,6156.682,NaN,NaN,NaN,NaN,6634.533,1488.776,20520.91,NaN,NaN,NaN,NaN,NaN,3908.034,NaN,NaN,5544.209,3584.901,3.911652,5758.457,NaN,45104.24,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,2018M05,4816.634,NaN,20025.570,28613.68,19284.530,41.77341,6488.860,NaN,19095.95,141796.80,NaN,11182.40,NaN,72648.360000,32471.670,1543.444,6800.308,48813.44,NaN,881951.4,37437.740,13304.16,773379.1,15366.10,3996.219,44487.98,536.9925,65406.70,55224.250,63589.58,NaN,40585.920,NaN,536.9925,21130.07,54085.41,9898.409,3336.622,108395.10,3719.128,8497.676,26393.16,27936.07,NaN,38430.160,NaN,9.767317,16014.380,20213.180,44712.290000,27710.600,NaN,136559.90,1233690.0
329,2018M06,4678.404,NaN,21514.230,28093.34,20220.210,43.83378,6309.378,NaN,19538.32,149851.60,NaN,11689.72,NaN,66017.910000,31705.800,1577.354,6815.096,54386.94,NaN,904458.4,36018.430,13946.08,801295.4,12177.46,3830.384,46200.48,NaN,72903.46,56117.010,63492.16,NaN,39207.420,NaN,NaN,20027.01,54919.82,9855.237,3064.864,103554.30,4064.532,9072.128,NaN,23695.94,NaN,36101.530,NaN,9.919567,16035.700,19859.370,42321.980000,26755.980,NaN,136749.60,1246063.0
330,2018M07,NaN,NaN,NaN,NaN,22464.320,NaN,NaN,NaN,17102.93,143851.30,NaN,11201.29,NaN,NaN,NaN,1480.100,6250.913,54029.10,NaN,876149.6,38191.040,NaN,766786.9,15551.63,NaN,46585.13,NaN,69377.07,57031.740,63498.60,NaN,37316.710,NaN,NaN,21851.78,52708.95,NaN,NaN,108037.30,3717.559,NaN,NaN,NaN,NaN,37948.720,NaN,NaN,13735.090,18668.800,48067.830000,27016.640,NaN,126438.50,1227797.0
331,2018M08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69069.11,56287.050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27080.790,NaN,NaN,NaN
332,2018M09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Correct the names of the countries

In [7]:
#rename countries 
new_columns=str()
for country in ER_data.columns : 
    if '0' in country : 
        new_column = country.replace('0','na')
        ER_data.rename(columns = {country:new_column}, inplace = True)

In [8]:
ER_data

,Period,Afghanistan,Angola,Albania,United Arab Emirates,Argentina,Armenia,Developing Asia,Antigua and Barbuda,Australia,Austria,Azerbaijan,Burundi,Belgium,Benin,Burkina Faso,Bangladesh,Bulgaria,Bahrain,Bahamas,Bosnia and Herzegovina,Belarus,Belize,Bolivia,Brazil,Barbados,Brunei Darussalam,Bhutan,Botswana,Central African Republic,Canada,Switzerland,Chile,China,Cote d'Ivoire,Cameroon,"Congo, Dem. Rep.","Congo, Rep.",Colombia,Comoros,Cabo Verde,Costa Rica,Cyprus,Czech Republic,Germany,Developing Countries,Djibouti,Dominica,Denmark,Dominican Republic,Algeria,East Asia & Pacific developing,Europe & Central Asia developing,Ecuador,"Egypt, Arab Rep.",Eritrea,Spain,Estonia,Ethiopia,Finland,Fiji,France,"Micronesia, Fed. Sts.",Gabon,United Kingdom,Georgia,Ghana,Guinea,"Gambia, The",Guinea-Bissau,Equatorial Guinea,Greece,Grenada,Guatemala,Guyana,High Income Countries,"Hong Kong SAR, China",Honduras,Croatia,Haiti,Hungary,High income: OECD,Indonesia,India,Ireland,"Iran, Islamic Rep.",Iraq,Iceland,Israel,Italy,Jamaica,Jordan,Japan,Kazakhstan,Kenya,Kyrgyz Republic,Cambodia,Kiribati,St. Kitts and Nevis,"Korea, Rep.",Kuwait,Latin America & Caribbean developing,"Lao, PDR",Lebanon,Liberia,Libya,St. Lucia,Low Income,Sri Lanka,Lesotho,Lithuania,Luxembourg,Latvia,Morocco,"Moldova, Rep.",Madagascar,Maldives,Mexico,Middle Income Countries,"Macedonia, FYR",Mali,Malta,Myanmar,Middle East & N. Africa developing,Montenegro,Mongolia,Mozambique,Mauritania,Mauritius,Malawi,Malaysia,namibia,Niger,Nigeria,Nicaragua,Netherlands,Norway,Nepal,New Zealand,High Income: Non-OECD,Oman,Pakistan,Panama,Peru,Philippines,Papua New Guinea,Poland,Portugal,Paraguay,West Bank and Gaza,Qatar,Romania,Russian Federation,Rwanda,South Asia developing,Saudi Arabia,Sudan,Senegal,Singapore,Solomon Islands,Sierra Leone,El Salvador,San Marino,Serbia,South Sudan,Sub-Saharan Africa developing,Sao Tome and Principe,Suriname,Slovakia,Slovenia,Sweden,Swaziland,Seychelles,Syrian Arab Republic,Chad,Togo,Thailand,Tajikistan,Turkmenistan,Timor-Leste,Tonga,Trinidad and Tobago,Tunisia,Turkey,"Taiwan, China","Tanzania, United Rep.",Uganda,Ukraine,Uruguay,United States,Uzbekistan,St. Vincent and the Grenadines,"Venezuela, RB",Vietnam,Vanuatu,World (WBG members),Samoa,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
0,1988M12,0.0,0.0000,0.0000,3.675,0.00000,0.0,190.3592,0.000000,1.164807,0.842486,0.000000,0.000,0.842486,0.0,0.0,0.00000,0.000000,0.378000,0.0,0.000000,0.00,0,0.00,0.000000,0.000000,0.000000,15.01773,0.00000,0.0,1.196500,1.480864,245.7682,3.731000,0.0000,0.0,0.000,0.0,0.000,0.0000,0.0,0.0000,0.842486,0.00000,0.842486,0.000,0.0,0.0,6.793227,0.00000,0.0000,263.5328,0.0000,1,0.00000,0.0,0.842486,0.842486,0.00000,0.842486,0.000000,0.842486,0,0.0,0.548072,0.000000,0.000000,0.000,0.00000,0.0,0.0,0.842486,0.0,0.000000,0.0,34.98479,7.806273,0.00000,0.000000,0.00000,0.0000,36.71427,0.00,15.01773,0.842486,0.0,0.0,0.0000,1.644909,0.842486,0.0000,0.514000,123.6641,0.0000,18.62000,0.00000,0.0,0.0,0.0,687.8727,0.278409,0.00,0.0,0.000,0.0,0.0,0.0,0.000,33.01864,2.349682,0.842486,0.842486,0.842486,8.337500,0.00000,0.000,0.00000,2.281000,0.000,0.00000,0.0,0.842486,0.0,0.0,0.0,0.000,0.00000,0.0000,0.00000,0.0000,2.694045,2.349682,0.0,0.0000,0.00000,0.842486,6.526227,0.0000,1.566983,0.000000,0.387955,18.64750,1,0.000000,0.00000,0.000000,0.000000,0.842486,0.000,1,3.642000,0.001000,0.00000,0.0000,16.17234,3.752000,0.0,0.0,1.944500,0.000000,0.000,0.00,0.0,0.0,0.0,0.0000,0.0,0.000000,0.842486,0.842486,6.091182,2.349682,0.00000,0.0,0.0,0.0,25.15591,0.0,0,0,0.000000,0.000000,0.885455,0.002000,28.19955,125.1250,0.000,0.00000,0.00000,1,0.000,0.0,0.0,0.00,0.0000,76.76546,0.000000,0.0000,2.349682,0.00000,0.0
1,1989M01,0.0,0.0000,0.0000,3.675,0.00000,0.0,191.0076,0.000000,1.148810,0.874694,0.000000,0.000,0.874694,0.0,0.0,0.00000,0.000000,0.378000,0.0,0.000000,0.00,0,0.00,0.000000,0.000000,0.000000,15.07864,0.00000,0.0,1.191909,1.560364,247.1382,3.731000,0.0000,0.0,0.000,0.0,0.000,0.0000,0.0,0.0000,0.874694,0.00000,0.874694,0.000,0.0,0.0,7.106364,0.00000,0.0000,264.0013,0.0000,1,0.00000,0.0,0.874694,0.874694,0.00000,0.874694,0.000000,0.874694,0,0.0,0.562866,0.000000,0.000000,0.000,0.00000,0.0,0.0,0.874694,0.0,0.000000,0.0,35.41262,7.805545,0.00000,0.000000,0.00000,0.0000,37.16490,0.00,15.07864,0.874694,0.0,0.0,0.0000,1.685000,0.874694,0.0000,0.529432,127.2977,0.0000,18.71409,0.00000,0.0,0.0,0.0,685.4045,0.284955,0.00,0.0,0.000,0.0,0.0,0.0,0.000,33.13114,2.385500,0.874694,0.874694,0.874694,8.371591,0.00000,0.000,0.00000,2.282318,0.000,0.00000,0.0,0.874694,0.0,0.0,0.0,0.000,0.00000,0.0000,0.00000,0.0000,2.722182,2.385500,0.0,0.0000,0.00000,0.874694,6.678818,0.0000,1.596001,3.029721,0.385909,18.91386,1,0.000000,0.00000,0.000000,0.000000,0.874694,0.000,1,3.642000,0.001000,0.00000,0.0000,16.25547,3.752000,0.0,0.0,1.941273,0.000000,0.000,0.00,0.0,0.0,0.0,0.0000,0.0,0.000000,0.874694,0.874694,6.268909,2.385500,0.00000,0.0,0.0,0.0,25.30182,0.0,0,0,1.136364,0.000000,0.921250,0.002000,27.92000,125.6875,0.000,0.00000,0.00000,1,0.000,0.0,0.0,0.00,0.0000,77.67523,0.000000,0.0000,2.385500,0.00000,0.0
2,1989M02,0.0,0.0000,0.0000,3.675,0.00000,0.0,191.9781,0.000000,1.169614,0.883210,0.000000,0.000,0.883210,0.0,0.0,0.00000,0.000000,0.378000,0.0,0.000000,0.00,0,0.00,0.000000,0.000000,0.000000,15.23600,0.00000,0.0,1.189250,1.573950,245.8500,3.731000,0.0000,0.0,0.000,0.0,0.000,0.0000,0.0,0.0000,0.883210,0.00000,0.883210,0.000,0.0,0.0,7.208200,0.00000,0.0000,264.2489,0.0000,1,0.00000,0.0,0.883210,0.883210,0.00000,0.883210,0.000000,0.883210,0,0.0,0.570153,0.000000,0.000000,0.000,0.00000,0.0,0.0,0.883210,0.0,0.000000,0.0,35.33238,7.801050,0.00000,0.000000,0.00000,0.0000,37.08043,0.00,15.23600,0.883210,0.0,0.0,0.0000,1.685000,0.883210,0.0000,0.547500,127.6755,0.0000,18.83050,0.00000,0.0,0.0,0.0,680.2200,0.288100,0.00,0.0,0.000,0.0,0.0,0.0,0.000,33.10250,2.458750,0.883210,0.883210,0.883210,8.433500,0.00000,0.000,0.00000,2.475000,0.000,0.00000,0.0,0.883210,0.0,0.0,0.0,0.000,0.00000,0.0000,0.00000,0.0000,2.730850,2.458750,0.0,0.0000,0.00000,0.883210,6.724150,0.0000,1.616534,3.028403,0.386000,19.06750,1,0.000000,0.00000,0.000000,0.000000,0.883210,0.000,1,3.642000,0.001000,0.00000,0.0000,16.40952,3.752550,0.0,0.0,1.928500,0.000000,0.000,0.00,0.0,0.0,0.0,0.0000,0.0,0.000000,0.883210,0.883210,6.323300,2.458750,0.00000,0.0,0.0,0.0,25.38350,0.0,0,0,1.168727,0.000000,0.940350,0.002000,27.70300,127.7250,0.000,0.00000,0.00000,1,0.000,0.0,0.0,0.00,0.0000,77.53630,0.000000,0.0000,2.458750,0.00000,0.0
3,1989M03,0.0,0.0000,0.0000,3.675,0.00000,0.0,193.4470,0.000000,1.223637,0.890488,0.000000,0.000,0.890488,0.0,0.0,0.00000,0.000000,0.378000,0.0,0.000000,0.00,0,0.00,0.000000,0.000000,0.000000,15.45522,0.00000,0.0,1.195565,1.611304,246.3096,3.731000,0.0000,0.0,0.000,0.0,0.000,0.0000,0.0,0.0000,0.890488,0.00000,0.890488,0.000,0.0,0.0,7.291391,0.00000,0.0000,264.5445,0.0000,1,0.00000,0.0,0.890488,0.890488,0.00000,0.890488,0.000000,0.890488,0,0.0,0.583451,0.000000,0.000000,0.000,0.00000,0.0,0.0,0.890488,0.0,0.000000,0.0,35.59831,7.797739,0.00000,0.000000,0.00000,0.0000,37.36052,0.00,15.45522,0.890488,0.0,0.0,0.0000,1.690870,0.890488,0.0000,0.538043,130.5509,0.0000,19.20130,0.00000,0.0,0.0,0.0,675.6761,0.290217,0.00,0.0,0.000,0.0,0.0,0.0,0.000,33.42804,2.539391,0.890488,0.890488,0.890488,8.475217,0.00000,0.000,0.00000,2.475000,0.000,0.00000,0.0,0.890488,0.0,0.0,0.0,0.000,0.00000,0.0000,0.00000,0.0000,2.753609,2.539391,0.0,0.0000,0.00000,0.890488,6.805957,0.0000,1.622369,3.029622,0.386217,19.41370,1,0.000000,0.00000,0.000000,0.000000,0.890488,0.000,1,3.642000,0.001000,0.00000,0.0000,16.64788,3.751783,0.0,0.0,1.939478,0.000000,0.000,0.00,0.0,0.0,0.0,0.0000,0.0,0.000000,0.890488,0.890488,6.393304,2.539391,0.00000,0.0,0.0,0.0,25.47174,0.0,0,0,1.241492,0.000000,0.943978,0.002000,27.61783,130.4565,0.000,0.00000,0.00000,1,0.000,0.0,0.0,0.00,0.0000,78.12339,0.000000,0.0000,2.539391,0.00000,0.0
4,1989M04,0.0,0.0000,0.0000,3.675,0.00000,0.0,195.0895,0.000000,1.243114,0.890342,0.000000,0.000,0.890342,0.0,0.0,0.00000,0.000000,0.378000,0.0,0.000000,0.00,0,0.00,0.000000,0.000000,0.000000,15.70650,0.00000,0.0,1.188900,1.646950,252.2410,3.731000,0.0000,0.0,0.000,0.0,0.000,0.0000,0.0,0.0000,0.890342,0.00000,0.890342,0.000,0.0,0.0,7.280400,0.00000,0.0000,264.6188,0.0000,1,0.00000,0.0,0.890342,0.890342,0.00000,0.890342,0.000000,0.890342,0,0.0,0.587579,0.000000,0.000000,0.000,0.00000,0.0,0.0,0.890342,0.0,0.000000,0.0,35.73175,7.783300,0.00000,0.000000,0.00000,0.0000,37.50110,0.00,15.70650,0.890342,0.0,0.0,0.0000,1.820000,0.890342,0.0000,0.538000,132.0390,0.0000,19.37300,0.00000,0.0,0.0,0.0,672.1200,0.290850,0.00,0.0,0.000,0.0,0.0,0.0,0.000,34.02350,2.548200,0.890342,0.890342,0.890342,8.491500,0.00000,0.000,0.00000,2.475000,0.000,0.00000,0.0,0.890342,0.0,0.0,0.0,0.000,0.00000,0.0000,0.00000,0.0000,2.721150,2.548200,0.0,0.0000,0.00000,0.890342,6.796500,0.0000,1.632956,3.029086,0.386000,19.84450,1,0.000000,0.00000,0.000000,0.000000,0.890342,0.000,1,3.642000,0.001000,0.00000,0.0000,16.93112,3.751050,0.0,0.0,1.950450,0.000000,0.000,0.00,0.0,0.0,0.0,0.0000,0.0,0.000000,0.890342,0.890342,6.369000,2.548200,0.00000,0.0,0.0,0.0,25.52250,0.0,0,0,1.215517,0.000000,0.944200,0.002000,26.96330,132.2250,0.000,0.00000,0.00000,1,0.000,0.0,0.0,0.00,0.0000,78.43185,0.000000,0.0000,2.548200,0.00000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2018M07,0.0,253.7293,107.8486,3.673,27.59330,0.0,1411.2090,2.699545,1.351000,0.855673,1.697886,1780.416,0.855673,0.0,0.0,83.93938,1.673773,0.379068,1.0,1.681886,19834.07,0,6.91,3.824659,2.000977,1.356864,68.73895,10.29523,0.0,1.313545,0.994386,651.9882,6.719159,571.6634,0.0,1619.955,0.0,2885.412,420.9956,0.0,567.7273,0.855673,22.11086,0.855673,5065.074,0.0,0.0,6.376886,49.50986,117.5970,1757.4950,832.0435,1,17.89689,0.0,0.855673,0.855673,27.47425,0.855673,2.099168,0.855673,0,0.0,0.759413,2.448727,4.758795,9067.929,48.00290,0.0,0.0,0.855673,0.0,7.494159,0.0,46.89484,7.847955,23.99052,6.330318,65.96814,277.7284,48.97821,14417.57,68.73895,0.855673,0.0,0.0,106.4664,3.644386,0.855673,131.6790,0.709909,111.4536,344.5050,100.65700,68.20334,0.0,0.0,0.0,1123.3590,0.302955,11791.61,0.0,1513.231,0.0,0.0,0.0,1208.711,159.41250,13.390480,0.855673,0.855673,0.855673,9.461523,16.67091,3357.551,15.48559,18.998020,5125.823,52.70632,0.0,0.855673,0.0,0.0,0.0,2461.981,58.74852,355.7223,34.40700,723.9305,4.050886,13.390430,0.0,361.5498,31.67789,0.855673,8.129114,110.0202,1.473530,8.361239,0.385000,124.50750,1,3.276886,53.42391,3.295889,3.699000,0.855673,5721.170,1,3.655477,3.978591,62.83027,872.0777,77.24887,3.750000,0.0,0.0,1.363523,7.917435,7955.466,8.75,0.0,0.0,0.0,422.1706,0.0,7.506227,0.855673,0.855673,8.819045,13.390430,13.51466,0.0,0.0,0.0,33.27314,0.0,0,0,2.252515,6.823409,2.639659,4.772955,30.56614,2276.7640,3758.407,26.42550,31.13893,1,7939.079,0.0,129724.0,23100.55,108.9250,1585.97000,2.590986,250.3023,13.390430,9.91025,0.0
356,2018M08,0.0,266.1822,108.9400,3.673,30.24126,0.0,1425.0790,2.701522,1.365333,0.866315,1.697261,1778.990,0.866315,0.0,0.0,83.92822,1.694652,0.377478,1.0,1.703457,20457.28,0,6.91,3.934891,2.000957,1.362348,69.61543,10.56340,0.0,1.304000,0.988348,659.4991,6.846739,578.5249,0.0,1620.630,0.0,2969.047,426.1813,0.0,569.9250,0.866315,22.25776,0.866315,7540.499,0.0,0.0,6.459543,49.76359,118.3935,1774.8050,853.8817,1,17.88170,0.0,0.866315,0.866315,27.63867,0.866315,2.114047,0.866315,0,0.0,0.776854,2.534913,4.771087,9092.230,48.74005,0.0,0.0,0.866315,0.0,7.510304,0.0,46.87079,7.849630,24.02078,6.433500,67.95363,279.9661,48.92625,14565.09,69.61543,0.866315,0.0,0.0,107.6504,3.661457,0.866315,136.2439,0.709739,111.0300,357.7837,100.62260,68.73267,0.0,0.0,0.0,1121.3310,0.303196,19285.43,0.0,1511.676,0.0,0.0,0.0,1209.265,160.43000,14.126610,0.866315,0.866315,0.866315,9.476239,16.61511,3311.368,15.52278,18.858090,7642.803,53.33830,0.0,0.866315,0.0,0.0,0.0,2461.687,58.89185,356.7776,34.49061,722.9528,4.094000,14.126780,0.0,362.2754,31.85150,0.866315,8.343261,111.4791,1.499446,8.853607,0.385000,122.98000,1,3.290413,53.29080,3.312218,3.712391,0.866315,5780.765,1,3.655174,4.022370,66.47593,877.2161,77.87157,3.750674,0.0,0.0,1.369000,7.898405,8219.295,8.75,0.0,0.0,0.0,423.7852,0.0,7.504261,0.866315,0.866315,9.075348,14.126980,13.46511,0.0,0.0,0.0,33.02228,0.0,0,0,2.266071,6.749413,2.743413,5.942696,30.71911,2280.9660,3733.038,27.57539,31.35428,1,7883.981,0.0,213716.5,23293.26,110.0105,2337.68100,2.585069,250.2846,14.126850,10.08304,0.0
357,2018M09,0.0,286.0590,108.5063,3.673,38.64783,0.0,1448.6440,2.700250,1.388744,0.857495,1.698000,1784.000,0.857495,0.0,0.0,83.82198,1.677375,0.377000,1.0,1.686150,21190.38,0,6.91,4.102400,2.000850,1.364325,72.22203,10.77763,0.0,1.303725,0.968175,679.4698,6.855400,578.7612,0.0,1621.375,0.0,3031.533,421.8135,0.0,581.0473,0.857495,21.97240,0.857495,7674.845,0.0,0.0,6.395825,49.89270,118.0113,1803.8840,880.2203,1,17.91505,0.0,0.857495,0.857495,27.68738,0.857495,2.127835,0.857495,0,0.0,0.765895,2.609200,4.841500,9095.692,49.26438,0.0,0.0,0.857495,0.0,7.663475,0.0,47.13862,7.837675,24.03953,6.369700,69.74503,278.4145,49.12397,14864.75,72.22203,0.857495,0.0,0.0,110.5850,3.589275,0.857495,136.5519,0.710000,112.0905,367.8721,100.84600,69.23965,0.0,0.0,0.0,1120.0010,0.303000,19669.19,0.0,1510.403,0.0,0.0,0.0,1219.691,165.20700,14.748180,0.857495,0.857495,0.857495,9.402350,16.78850,3412.167,15.50110,19.001850,7780.309,52.81013,0.0,0.857495,0.0,0.0,0.0,2496.553,60.44695,357.3950,34.35160,724.0691,4.140725,14.748230,0.0,362.6958,32.10425,0.857495,8.245500,115.6587,1.515368,10.418460,0.385000,123.19080,1,3.310250,53.97598,3.326139,3.686425,0.857495,5854.810,1,3.659225,3.982600,67.60390,878.9235,80.18285,3.750825,0.0,0.0,1.371350,7.960640,8336.868,8.75,0.0,0.0,0.0,427.8830,0.0,7.496150,0.857495,0.857495,8.945150,14.748280,13.53465,0.0,0.0,0.0,32.59703,0.0,0,0,2.280193,6.766200,2.777425,6.297250,30.74175,2283.0420,3800.272,28.18975,32.87670,1,8018.261,0.0,0.0,23286.50,111.1823,2376.23400,2.603659,250.2786,14.748280,10.94930,0.0
358,2018M10,0.0,303.7345,109.0561,3.673,37.06159,0.0,1473.6990,2.704348,1.407934,0.870907,1.696370,1799.053,0.870907,0.0,0.0,84.52207,1.703630,0.377000,1.0,1.705174,21256.09,0,6.91,3.760022,2.000891,1.372109,73.58743,10.73582,0.0,1.301826,0.993913,679.5872,6.926804,585.1240,0.0,1623.293,0.0,3095.854,428.4075,0.0,595.9065,0.870907,22.49357,0.870907,7796.166,0.0,0.0,6.496565,49.96380,118.7490,1834.9400,884.4504,1,17.91526,0.0,0.870907,0.870907,27.88339,0.870907,2.144862,0.870907,0,0.0,0.768699,2.662804,4.873130,9130.136,49.99641,0.0,0.0,0.870907,0.0,7.728457,0.0,47.50429,7.838043,24.06996,6.465326,71.26059,281.9780,49.52488,15177.11,73.58743,0.870907,0.0,0.0,117.2176,3.657239,0.870907,132.0431,0.709783,112.7609,367.1807,101.11020,69.26480,0.0,0.0,0.0,1131.2240,0.303522,20053.73,0.0,1510.775,0.0,0.0,0.0,1223.629,171.52650,14.536870,0.870907,0.870907,0.870907,9.486413,17.01315,3495.812,15.45728,19.218090,7905.141,53.60380,0.0,0.870907,0.0,0.0,0.0,2562.718,60.38548,356.9950,34.51874,727.9566,4.158522,14.536870,0.0,363.3820,32.16039,0.870907,8.259848,117.7762,1.532541,10.132090,0.385000,129.90450,1,3.334696,53.94120,3.355461,3.749739,0.870907,5953.722,1,3.659130,4.062804,65.86035,876.9750,82.12067,3.751109,0.0,0.0,1.379674,8.017561,8415.225,8.75,0.0,0.0,0.0,430.3051,0.0,7.514413,0.870907,0.870907,9.050152,14.536910,13.62441,0.0,0.0,0.0,32.79483,0.0,0,0,2.271729,6.740674,2.841348,5.819891,30.88115,2287.3500,3780.230,28.11041,32.90704,1,8209.098,0.0,0.0,23323.63,111.3950,2411.72600,2.632711,250.2947,14.536910,11.88980,0.0
359,2018M11,0.0,309.2843,109.4100,3.673,35.60083,0.0,1445.6860,2.710000,1.383155,0.876683,1.697167,1797.333,0.876683,0.0,0.0,83.78050,1.715000,0.377000,1.0,1.722000,21241.25,0,6.91,3.730000,1.997500,1.367000,73.00600,10.63910,0.0,1.311333,1.003833,681.0383,6.919500,593.5750,0.0,1618.167,0.0,3165.912,431.1355,0.0,622.7500,0.876683,22.65817,0.876683,7686.535,0.0,0.0,6.540333,49.92633,118.5503,1799.6840,885.2643,1,17.91783,0.0,0.876683,0.876683,28.01483,0.876683,2.123943,0.876683,0,0.0,0.766003,2.732500,4.847833,9141.518,49.80500,0.0,0.0,0.876683,0.0,7.714333,0.0,47.41194,7.829667,24.13358,6.519667,65.27580,282.1483,49.44216,14815.67,73.00600,0.876683,0.0,0.0,121.0950,3.683167,0.876683,127.5383,0.709667,113.3717,371.0100,101.68830,69.78783,0.0,0.0,0.0,1124.3120,0.304000,20464.05,0.0,1513.667,0.0,0.0,0.0,1223.691,174.51670,14.182830,0.876683,0.876683,0.876683,9.505667,17.09083,3564.695,15.53967,19.964000,7791.901,53.92183,0.0,0.876683,0.0,0.0,0.0,2561.630,60.65500,356.9950,34.63333,728.4688,4.168750,14.182830,0.0,363.2717,32.21333,0.876683,8.359500,117.1140,1.492633,9.861645,0.385000,133.56900,1,3.363500,53.01167,3.365120,3.771000,0.876683,5957.000,1,3.654833,4.086167,66.18917,891.1267,82.00213,3.751000,0.0,0.0,1.374333,8.043360,8429.246,8.75,0.0,0.0,0.0,430.8004,0.0,7.478667,0.876683,0.876683,9.042667,14.183000,13.49983,0.0,0.0,0.0,32.90383,0.0,0,0,2.265871,6.743500,2.886833,5.416167,30.73967,2287.6550,3748.623,27.98317,32.75317,1,8251.382,0.0,0.0,23318.17,110.4588,2380.95300,2.604273,250.2600,14.183170,11.78267,0.0

In [9]:
ER_data.rename(columns = {'Period':'Year'}, inplace = True)

### Filling missing values

In [10]:
Exports_data=Exports_data.fillna(0)
ER_data=ER_data.fillna(0)
CPI_data=CPI_data.fillna(0)

### Add missing countries

In [11]:
CPI_columns = set(CPI_data.columns)
ER_columns= set(ER_data.columns)
Exports_columns=set(Exports_data.columns)
not_inCPI = list(ER_columns.union(Exports_columns) - CPI_columns)
not_inER = list(CPI_columns.union(Exports_columns) - ER_columns)
not_inExports = list(CPI_columns.union(ER_columns) - Exports_columns)

In [12]:
CPI_data[not_inCPI]=0
ER_data[not_inER]=0
Exports_data[not_inExports]=0

C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0
C:\Users\rayen\AppData\Local\Temp\ipykernel_6596\4142656040.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Exports_data[not_inExports]=0

### Adding missing dates

In [15]:
CPI_dates=set(CPI_data['Year'].values)
ER_dates=set(ER_data['Year'].values)
Exports_dates=set(Exports_data['Year'].values)
Dates_notInCPI= list(ER_dates.union(Exports_dates) - CPI_dates)
Dates_notInER= list(CPI_dates.union(Exports_dates) - ER_dates)
Dates_notInExports= list(ER_dates.union(CPI_dates) - Exports_dates)

In [16]:
additional_dataframe = pd.DataFrame(columns=Exports_data.columns)
additional_dataframe['Year']=Dates_notInExports 
Exports_cols=[col for col in Exports_data.columns if col!="Year"]
additional_dataframe[Exports_cols]=0
Exports_data=pd.concat([additional_dataframe,Exports_data])

In [17]:
Exports_data.shape

(360, 202)

In [18]:
CPI_data.shape

(360, 202)

In [19]:
ER_data.shape

(360, 202)

### Reformat Dataframes

In [22]:
countries=[country for country in CPI_data if country!='Year']
CPI_data_formatted = CPI_data.melt(id_vars='Year', value_vars=countries, var_name='Country', value_name='CPI_score')
countries2=[country for country in ER_data if country!='Year']
ER_data_formatted = ER_data.melt(id_vars='Year', value_vars=countries2, var_name='Country', value_name='ER')
countries3=[country for country in Exports_data if country!='Year']
Exports_data_formatted = Exports_data.melt(id_vars='Year', value_vars=countries3, var_name='Country', value_name='ER')

In [23]:
Exports_data_formatted.shape

(72360, 3)

In [24]:
ER_data_formatted.shape

(72360, 3)

In [25]:
CPI_data_formatted.shape

(72360, 3)

### Datetime format

In [26]:
CPI_data_formatted.rename(columns = {'Year':'Date'}, inplace = True)
ER_data_formatted.rename(columns = {'Year':'Date'}, inplace = True)
Exports_data_formatted.rename(columns = {'Year':'Date'}, inplace = True)
CPI_data_formatted['Date']=pd.to_datetime(CPI_data_formatted['Date'], format='%YM%m')
ER_data_formatted['Date']=pd.to_datetime(ER_data_formatted['Date'], format='%YM%m')
Exports_data_formatted['Date']=pd.to_datetime(Exports_data_formatted['Date'], format='%YM%m')

In [27]:
Exports_data_formatted

            Date    Country   ER
0     1989-07-01  Argentina  0.0
1     1990-02-01  Argentina  0.0
2     1989-05-01  Argentina  0.0
3     1990-09-01  Argentina  0.0
4     1990-10-01  Argentina  0.0
...          ...        ...  ...
72355 2018-05-01   Pakistan  0.0
72356 2018-06-01   Pakistan  0.0
72357 2018-07-01   Pakistan  0.0
72358 2018-08-01   Pakistan  0.0
72359 2018-09-01   Pakistan  0.0

[72360 rows x 3 columns]

In [28]:
ER_data_formatted

            Date      Country   ER
0     1988-12-01  Afghanistan  0.0
1     1989-01-01  Afghanistan  0.0
2     1989-02-01  Afghanistan  0.0
3     1989-03-01  Afghanistan  0.0
4     1989-04-01  Afghanistan  0.0
...          ...          ...  ...
72355 2018-07-01      Namibia  0.0
72356 2018-08-01      Namibia  0.0
72357 2018-09-01      Namibia  0.0
72358 2018-10-01      Namibia  0.0
72359 2018-11-01      Namibia  0.0

[72360 rows x 3 columns]

In [29]:
CPI_data_formatted

            Date                Country  CPI_score
0     1988-12-01            Afghanistan        0.0
1     1989-01-01            Afghanistan        0.0
2     1989-02-01            Afghanistan        0.0
3     1989-03-01            Afghanistan        0.0
4     1989-04-01            Afghanistan        0.0
...          ...                    ...        ...
72355 2018-07-01  Micronesia, Fed. Sts.        0.0
72356 2018-08-01  Micronesia, Fed. Sts.        0.0
72357 2018-09-01  Micronesia, Fed. Sts.        0.0
72358 2018-10-01  Micronesia, Fed. Sts.        0.0
72359 2018-11-01  Micronesia, Fed. Sts.        0.0

[72360 rows x 3 columns]